[package]
name = "combustion_r"
version = "2.0.4"
authors = ["002", "brainthinks"]

[dependencies]
tritium = {git="https://github.com/brainthinks/Tritium", branch="feature/rust_1.24"}
byteorder = "*"

[lib]
crate-type = ["staticlib", "dylib"]
